[package]
name = "thrift_test"
version = "0.1.0"
authors = ["jiaxin.shui <jiaxin.shui@yitu-inc.com>"]
edition = "2015"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thrift = {path = "../thrift/lib/rs"}